### ISSUE TITLE
Find better project/repo name

### ISSUE THREAD

**Issue by mickaelistria** [mickaelistria/eclipseide-jdtls#28]
As we plan to move it to be bigger organization (redhat-developers), we need to find a better name for the repo so people can more easily guess what it's about just by its name.

**Comment by mickaelistria** [comment]
As I like descriptive names, my current best idea would be "JDT.LS-powered-Eclipse.IDE"

**Comment by akurtakov** [comment]
I like  `eclipseide-jdtls`

**Comment by mickaelistria** [comment]
@rgrunber @ericwill OK for `eclipseide-jdtls` ?

**Comment by rgrunber** [comment]
Yeah, I'm fine with that. Other possibilities are `jdtls4e`, which should also be understood.

**Comment by ericwill** [comment]
I am fine with either `eclipseide-jdtls` or `jdtls4e`.
